version: '3.3'

services: 
  web:
    container_name: 'kevin_payment_web'
    build:
      context: ./web
    volumes: 
      - ./web:/app
    ports:
      - "3010:3000"
    
  api: 
    container_name: 'kevin_payment_api'
    build:
      context: ./api
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./api:/var/www
    networks:
      - kevin_bridge
      
  nginx:
    container_name: 'kevin_payment_nginx'
    image: nginx:latest
    restart: unless-stopped
    tty: true
    ports:
      - "8010:80"
    volumes:
      - ./api:/var/www
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/etc/log/nginx
    networks:
      - kevin_bridge

networks:
  kevin_bridge:
    driver: bridge
    